### ISSUE TITLE
Use AR instead of GCR for Deployments

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/kubernetes-engine-samples#209]
We are trying to encourage customers to use AR (Artifact Registry) instead of GCR (Google Container Registry).
So all [Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) in our GKE samples (in this repo) need to use AR-hosted images instead of GCR-hosted images.

## Example
For instance, the following `hello-app:1.0` Deployment 
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/hello-app/manifests/helloweb-deployment.yaml#L35 should change to:
```yaml
image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
```

## TODOs
Here are the files that need to be updated (and their associated pull-requests):

- [x] [migrating-node-pool/node-pools-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/migrating-node-pool/node-pools-deployment.yaml)
  * #210
- [x] [cloud-pubsub/deployment/pubsub-with-secret.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/cloud-pubsub/deployment/pubsub-with-secret.yaml)
  * #220
- [x] [cloud-pubsub/deployment/pubsub.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/cloud-pubsub/deployment/pubsub.yaml)
  * #220
- [x] [custom-metrics-autoscaling/direct-to-sd/custom-metrics-sd.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/custom-metrics-autoscaling/direct-to-sd/custom-metrics-sd.yaml)
  * #226 
- [x] [custom-metrics-autoscaling/prometheus-to-sd/custom-metrics-prometheus-sd.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/custom-metrics-autoscaling/prometheus-to-sd/custom-metrics-prometheus-sd.yaml)
  * #226 
- [x] [hello-app/manifests/helloweb-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/hello-app/manifests/helloweb-deployment.yaml)
  * #219
- [x] [hello-app-redis/manifests/app-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/hello-app-redis/manifests/app-deployment.yaml)
  * #227
- [x] [hello-app-tls/manifests/helloweb-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/hello-app-tls/manifests/helloweb-deployment.yaml)
  * #228
- [x] [load-balancing/web-deployment-v2.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/load-balancing/web-deployment-v2.yaml)
  * #219
- [x] [load-balancing/web-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/load-balancing/web-deployment.yaml)
  * #219
- [x] [whereami/k8s/deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/whereami/k8s/deployment.yaml)
  * #259
- [x] [whereami/k8s-grpc/deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/whereami/k8s-grpc/deployment.yaml)
  * #259
- [x] [guestbook/frontend-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/guestbook/frontend-deployment.yaml)
  * #194
- [x] [guestbook/redis-follower-deployment.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/guestbook/redis-follower-deployment.yaml)
  * #194
- [x] [guestbook/all-in-one/frontend.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/guestbook/all-in-one/frontend.yaml)
  * #194
- [x] [guestbook/all-in-one/guestbook-all-in-one.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/guestbook/all-in-one/guestbook-all-in-one.yaml)
  * #194
- [x] [guestbook/all-in-one/redis-follower.yaml](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/75e3523f6f0520864524c54cb7cb89c09932eb86/guestbook/all-in-one/redis-follower.yaml)
  * #194

## Concerns
* Before updating each of the above files, we need to make sure that the associated GKE tutorials still make sense (i.e., if the tutorial contains a step that pushes to GCR, we need to update the tutorial as well).

**Comment by NimJay** [comment]
I am closing this as all Kubernetes Deployments in this repository now use AR samples — instead of GCR samples! 🎈
